axiomhq/cli

- cmd/axiom/ingest/ingest.go
Clarify supported input formats, -f switch usage, and what the -c switch means.
> Clarify some help strings for the ingest command

- README.md
- cmd/axiom/auth/auth_login.go
Make the deployment just logged into the default (selected) one.
Closes #11
> Fix auth login

- cmd/axiom/ingest/ingest.go
- cmd/axiom/main.go
> Drop ingest compression flag

- cmd/axiom/auth/auth_login.go
> Auth login example

- cmd/axiom/auth/auth_login.go
> Specify valid values for `--token-type`

- cmd/axiom/ingest/ingest.go
This fixes a bug where no data is sent if the stream is stalled.
With this change we scan in another go func and provide individual lines on a channel, so if the stream blocks we're still able to go into the ticker branch.
Fixes #24
> Scan in a go func when --flush-every is set

- cmd/axiom/auth/auth.go
- cmd/axiom/auth/auth_login.go
- cmd/axiom/auth/auth_updatetoken.go
- internal/cmdutil/chain.go
Closes #35.
I initially played around with running the command right after the prompt but failed to do so with various approaches. On the other hand, this resolves the issue. We can get fancier at a later point in time.
> `axiom auth update-token` command

- cmd/axiom/auth/auth_login.go
- cmd/axiom/auth/auth_status.go
- cmd/axiom/auth/auth_updatetoken.go
- cmd/axiom/root/root.go
- internal/client/client.go
- internal/cmdutil/factory.go
- internal/config/config.go
- pkg/surveyext/validation.go
* Add a flag to skip certificate validation
* Don't require the url scheme when configuring a deployment and default to https when not set
> Insecure flag + default scheme https

- cmd/axiom/ingest/ingest.go
> Copy bytes from scanner before sending on channel

- cmd/axiom/ingest/ingest.go
- internal/cmdutil/chain.go
- pkg/iofmt/table.go
> Fix ingest token usage

- .github/workflows/go.yml
- README.md
- go.sum
Included two mini fixes here: Running `go mod tidy` and adding `axiom dataset trim` to the `README.md`.
> Update GoReport Card

- cmd/axiom/dataset/dataset_create.go
- cmd/axiom/dataset/dataset_delete.go
- cmd/axiom/dataset/dataset_info.go
- cmd/axiom/dataset/dataset_list.go
- cmd/axiom/dataset/dataset_stats.go
- cmd/axiom/dataset/dataset_trim.go
- cmd/axiom/dataset/dataset_update.go
- cmd/axiom/ingest/ingest.go
- cmd/axiom/stream/stream.go
Needs axiomhq/axiom-go#30 for Axiom 1.6 support.
> CSV delimiter support

- cmd/axiom/auth/auth_login.go
- cmd/axiom/auth/auth_status.go
- cmd/axiom/auth/auth_update_token.go
- cmd/axiom/ingest/ingest.go
- cmd/axiom/version/version.go
- go.mod
- go.sum
- internal/client/client.go
- internal/cmdutil/chain.go
- internal/cmdutil/factory.go
- pkg/surveyext/validation.go
Bump axiom-go and use the new token identification functions.
> Bump axiom-go to v0.1.2

- go.mod
- internal/config/config.go
> Drop go-homedir

- internal/cmd/ingest/ingest.go
> Better docs on Unix timestamps

- internal/cmd/root/help.go
Closes #https://github.com/axiomhq/cli/issues/106.
> Fix broken docs ref in help command output

- internal/cmd/query/query.go
I had a need for this, which was admitedly mostly driven for lazyness. but I just wanted to check the last hour in my query, and doing that with --start-time was a bit of a pain when I had to make timestamps 
so this PR allows for duration timestamps in --start/end-time. for example:
```bash
./cmd/axiom query "['jaeger'] | sort by _time" --format json --start-time="-1h"
``` 
I'm not super invested in this so if it's not what we want for the cli that's fine too, this just took me five minutes to make so why not
> make query start/endtimes relative capable

- cmd/axiom/main.go
- go.mod
- go.sum
- internal/cmd/auth/auth_login.go
Fixes misbehaviour on Windows.
> Switch to pkg/browser

- internal/cmdutil/chain.go
Closes https://github.com/axiomhq/cli/issues/133.
> fix(internal): 'axiom login' -> 'axiom auth login'

- README.md
- internal/cmd/root/root.go
- internal/cmd/web/web.go
Figured this would be a low hanging fruit.
> feat(cmd): add 'web' command to open cloud.axiom.co in browser

- internal/cmd/query/query.go
This is a rather naive attempt at improving the APL query result handling. Although it is not very nice, it does the job. Now queries with aggregations work properly. This definetly needs a cleanup when the new result format is available.
> fix(query): proper apl query result printing

- README.md
- internal/cmd/dataset/dataset.go
- internal/cmd/dataset/dataset_create.go
- internal/cmd/dataset/dataset_delete.go
- internal/cmd/dataset/dataset_trim.go
- internal/cmd/dataset/dataset_update.go
- internal/cmd/ingest/ingest.go
- internal/cmd/query/query.go
- internal/cmd/root/root.go
- internal/cmd/stream/stream.go
- internal/cmdutil/chain.go
Introduce a more generic example for ingesting data.
See issue for context.
Fixes #146.
I also sneaked in a small improvement to the README.
> docs: fix outdated nginx ingest example

- .github/workflows/pr.yaml
- .github/workflows/push.yaml
- .github/workflows/release.yaml
- Makefile
- README.md
- go.mod
Go toolchain update and some README / CI fixes for an upcoming minor release.
> chore: toolchain update

- .github/workflows/release.yaml
- internal/cmd/query/query.go
> feat(ci): add aur secret to release workflow

- internal/cmd/auth/auth_login.go
> fix: drop selfhost hack

- internal/cmd/stream/stream.go
This uses cursors and hard-codes the ordering.
> fix(stream): use cursors and _time ordering

- .golangci.yaml
- .goreleaser.yaml
- Makefile
- internal/cmd/ingest/ingest.go
- internal/cmd/root/help.go
- tools/loggen/main.go
> chore: go 1.23
