internal/cmdutil/chain.go

We can have an active deployment configured via env vars so there's no sense in requiring a configured deployment.
Fixes #28

Remove deployment check if we need an active one

---

README.md

@thecraftman Sorry, really not much to add. Maybe for the DockerHub README, it is sufficient enough to copy most of the README, but omit the non-docker installation methods?

Minimal docker docs

---

cmd/axiom/dataset/dataset.go
cmd/axiom/root/help.go
cmd/axiom/root/help_topic.go
cmd/axiom/root/root.go
cmd/axiom/stream/stream.go
cmd/axiom/version/version.go
internal/cmdutil/chain.go
internal/config/config.go

This PR improves the user experience by adding two things:
* An additional help topic on the different token types and how they affect the CLI usage
* An explicit error message when running commands which do not support using an ingest-only token
Overriding the token by flag or environment bypasses the check by assuming a personal token was passed. This is crucial because a deployment can be configured with an ingest token but a personal token can be specified as override.

Improve help on tokens

---

internal/cmdutil/chain.go

An oversight that occurs when nothing is configured by file, env or flag.

Fix "Error: No options to select from"

---

.goreleaser.yml
Makefile

* Enable buildmode `pie` for all platforms expect `linux/386` (not supported)
* While at it, build binaries for new M1 Macs by enabling `darwin/amd64`

Enable buildmode 'pie'

---

cmd/axiom/ingest/ingest.go

Discovered a panic while trying to find a fix for #70. Also removed some bad documentation on the `ingest` command.

Fix panic when running 'axiom ingest' without dataset argument

---

cmd/axiom/root/root.go
pkg/terminal/io.go

Adds a global `--no-spinner` flag to disable the spinner on the command line. This is useful, when tools in a pipe produce output as well, like `pv` in `cat myfile | pv | axiom ingest mydataset`.
Closes #81.

Add '--no-spinner' flag to disable spinner

---

.github/workflows/dependent_pr.yml
.github/workflows/pr.yml
.github/workflows/push.yml
.github/workflows/release.yml
README.md

* Run Go unit tests and binary integration test on all major three OS
* Only update coverage and and code quality report from tests that ran on ubuntu linux
* Introduce `AXIOM_DATASET_PREFIX` as in `axiom-node` and `axiom-go` to uniquely identify a test dataset if it should be left over
* Skip Go installation for the `lint` action
* Use `github.token` instead of `secrets.GITHUB_TOKEN`. The reason for this is that to unexperienced users it looks like `GITHUB_TOKEN` is configured as a repository secret like all the other secretes for the `secrets.*` key. This makes it a bit more implicit, where the token comes from.
* Some README fixes

Improved testing

---

README.md
internal/cmd/config/config.go
internal/cmd/config/config_export.go

This PR adds an export command to enable users of the CLI to export their configuration to environment variables.

Add export command

---

internal/cmd/auth/auth_login.go
internal/cmd/auth/auth_select.go
internal/cmd/auth/auth_switch_org.go
internal/cmd/organization/organization.go
internal/cmd/organization/organization_info.go
internal/cmd/organization/organization_license.go
internal/cmd/organization/organization_list.go

This PR changes (and unifies) how organizations are listed when a user needs to select one (for auth, switching organizations, etc.). Instead of displaying the organizations ID, its display name is listed with the organizations ID alongside it.

feat(cmd): improve organization listing

---

.goreleaser.yaml

We use that for most of our non-Go projects as well.

feat(ci): use GitHub release notes generation API for changelog

---

internal/cmd/ingest/ingest.go

We weren't displaying errors correctly, e.g.:
`Mon, 08 Aug 2022 07:51:34 CEST: %!s(<nil>) `
---------
Added a processedBytes line separately, due to potential misleading data (due to processedBytes counting failed and successful events combined):
✓ Ingested 9 events (1.2 MB) // <--total size wrong, should be couple kbs
✖ Failed to ingest 1 event: // <-- this one is 1.2 MB large.
---------
If anyone has a better idea of how to display the processed bytes, e.g. wording, placement, all feedback is welcome.

error display fix, processedBytes less misleading

---

internal/cmd/auth/auth_login.go
internal/cmd/auth/auth_logout.go
internal/cmd/auth/auth_select.go
internal/cmd/auth/auth_switch_org.go
internal/cmd/dataset/dataset_delete.go
internal/cmd/dataset/dataset_trim.go
internal/cmd/dataset/dataset_update.go
internal/cmd/ingest/ingest.go
internal/cmd/root/help_topic.go
internal/cmd/stream/stream.go
internal/cmdutil/chain.go

Some code grooming:
1. Fixes a misplaced `defer` statement
2. Makes the first item in a slice the default for `select` terminal ui elements
3. Add help topic on exit codes

chore: code grooming

---

.github/workflows/pr.yaml
.github/workflows/push.yaml
.github/workflows/release.yaml
go.mod

Update CI to use a more recent Go version and utilize the `setup-go` action more properly.

feat: update ci

---

internal/cmd/ingest/ingest.go

When the previous block returns an error, ingestRes may be nil, which caused a panic.

cmd/ingest: fix nil pointer deref

---

internal/cmd/root/help_topic.go
internal/cmdutil/chain.go
pkg/doc/doc.go

Some fixes to how documentation/help output is displayed in the terminal. Content is now word-wrapped after 80 instead of 120 characters (or terminal width, if that is less, but that was the case, previously).
Also contains some typo fixes.
Thanks @popey! <3

fix: terminal output

---

internal/client/client.go
internal/cmd/root/help_topic.go

This commit adds support for the standard HTTPS_PROXY and HTTP_PROXY env vars, which allows inspection of HTTP requests with proxies such as mitmproxy, aiding debugging.

client: support HTTPS_PROXY and HTTP_PROXY

---

.goreleaser.yaml

In reference to the following:
https://goreleaser.com/deprecations/#archivesrlcp
https://goreleaser.com/deprecations/#brewstap
The keys have been either removed or replaced accordingly.

Goreleaser deprecated keys removal/replacement.

---

internal/client/client.go

We saw issues where the - indeeed very small - dial timeout could kick in when Go's resolver took to long to lookup a hostname, which resulted in `i/o timeout` errors.
This PR uses the transport options from `axiom-go` but respecting some options we exlusively added in Axiom CLI, e.g. `Proxy`.

fix(client): use axiom-go http transport options

---

internal/cmd/ingest/ingest.go

Sleep on some loops when no inputs is available.
Closes #90.

Sleep when no input is available while streaming

---

.golangci.yaml
internal/cmd/ingest/ingest.go
internal/cmd/query/query.go

CSV should be batchable as well!
Also adds the CSV headers feature for CSV files without a header row.
In line with https://github.com/axiomhq/axiom-go/pull/305, I also addressed the batching behaviour here and made it less aggressive in time (flush batch every 5s instead of every 1s) but also introduced batch size based flushing (every 10k), whatever condition is met first. Also files are now batched instead of only `stdin` data.

feat(ingest): support setting fields for csv without header row + csv batching

---

.github/workflows/pr.yaml
.github/workflows/push.yaml
.goreleaser.yaml

Had a bad archive config. Fixed it and also changed CI to run `goreleaser --snapshot` to mitigate this in the future.
Also includes a fix for #290.

goreleaser: fix bad archive config

---

.goreleaser.yaml
README.md

Need this to successfully use the `axiom` cask.

cli: fix homebrew cask archive extraction and remove deprecated conflicts
